[versions]
commons-cli = "1.11.0"
bcprov = "1.84"
coroutines = "1.11.0"
jssc = "2.10.2"
kotlin = "2.4.0"

[libraries]
commons-cli = { module = "commons-cli:commons-cli", version.ref = "commons-cli" }
bcprov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bcprov" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jssc = { module = "io.github.java-native:jssc", version.ref = "jssc" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
